name: Check Steam Workshop IDs

on:
  push:
    paths:
      - 'cs2/**/MapChooser/maps.txt'  # 当任何 maps.txt 文件发生变化时触发
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 */6 * * *'  # 每 6 个小时触发一次

jobs:
  check-workshop-ids:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maps_path:
          - 'cs2/kz/counterstrikesharp/configs/plugins/MapChooser/maps.txt'
          - 'cs2/mg/counterstrikesharp/configs/plugins/MapChooser/maps.txt'
          # 在这里添加更多的 maps.txt 文件路径

    steps:
    - name: 检出代码库
      uses: actions/checkout@v3
      with:
        ref: master  # 确保检出的是主分支
        fetch-depth: 0  # 获取完整提交历史

    - name: 计算分支名称
      id: branch_name
      run: echo "branch_name=disable-unavailable-ids-$(echo ${{ matrix.maps_path }} | md5sum | cut -d ' ' -f 1)" >> $GITHUB_ENV

    - name: 删除现有的 disable-unavailable-ids 分支
      run: |
        git branch -D ${{ env.branch_name }} || true
        git push origin --delete ${{ env.branch_name }} || true

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: 运行检查脚本
      id: check_script
      run: |
        python scripts/check_workshop_ids.py ${{ matrix.maps_path }}
      continue-on-error: true

    - name: 读取不可用的 IDs
      if: failure()
      id: read_unavailable_ids
      run: |
        if [ -f unavailable_ids.txt ]; then
          ids=$(cat unavailable_ids.txt)
          echo "unavailable_ids=$ids" >> $GITHUB_ENV
        fi

    - name: 输出结果
      run: |
        if [ "${{ steps.check_script.outcome }}" == "failure" ]; then
          echo -e "\033[91m部分 Steam Workshop IDs 不可用。\033[0m"
          exit 1
        else:
          echo -e "\033[92m所有 Steam Workshop IDs 均可用。\033[0m"
        fi

    - name: 创建拉取请求
      if: failure()  # 仅在上一步失败时触发
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: 禁用不可用的 Steam Workshop IDs
        title: 禁用不可用的 Steam Workshop IDs
        body: |
          部分 Steam Workshop IDs 不可用。已将其对应的 enabled 字段从 1 改为 0。

          不可用 ID 列表:
          ${{ env.unavailable_ids }}

          请审核并确认更改。
        branch: ${{ env.branch_name }}
        base: master
